name: CI
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Create package
        run: zip -r release.zip build
      - name: copy file via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "release.zip"
          target: /home/assada/ut3usw.dead.guru/
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/assada/ut3usw.dead.guru/ && rm -rf /home/assada/ut3usw.dead.guru/build && unzip release.zip && rm release.zip && docker compose restart

      - name: IRC notification
        uses: Gottox/irc-message-action@v2
        with:
          channel: '#dead'
          nickname: GitHub
          server: 'irc.dead.guru'
          notice: true
          message: |-
            ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}

      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            ✅ VIEW: https://ut3usw.dead.guru
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}